export { BudgetExceededError, BudgetGuard } from "./budget.ts";
export { PolymarketClient } from "./polymarket.ts";
export { OllamaProvider } from "./providers/ollama.ts";
export { OpenRouterProvider } from "./providers/openrouter.ts";
export { ResearchClient } from "./research-client.ts";
export { SearxngSearchProvider } from "./search/searxng.ts";
export { SerperSearchProvider } from "./search/serper.ts";
export type { SerperOptions } from "./search/serper.ts";
export { FallbackSearchProvider } from "./search/fallback.ts";
export type { NamedSearchProvider } from "./search/fallback.ts";
export { PageContentFetcher } from "./search/page-content.ts";
export type { SearchHit } from "./search/page-content.ts";
export { FileRunStore } from "./storage/file-store.ts";
export { extractArenaSnapshot, renderArenaSnapshot, compareBoardDate } from "./arena.ts";
export type { ArenaSnapshot, ArenaRow } from "./arena.ts";
export { buildArenaEvidenceBrief } from "./evidence-brief.ts";
export type { ArenaEvidenceBrief, LabEvidence, EvidencePassage } from "./evidence-brief.ts";
export { evaluateRun, loadEvaluationCases } from "./eval.ts";
export type { CriterionResult, EvaluationCase, EvaluationCriterion, EvaluationKind, EvaluationResult } from "./eval.ts";
export type * from "./types.ts";

export { selectEvidence, canonicalSourceUrl } from "./evidence.ts";
export type { EvidencePolicy, EvidenceSelection } from "./evidence.ts";
export { PythSourceAdapter, PortWatchSourceAdapter, collectAdapterSources, extractSourceUrls } from "./source-adapters.ts";
export type { SourceAdapter, SourceAdapterContext, SourceAdapterResult, AdapterDiagnostic } from "./source-adapters.ts";
