use_default_settings: true

general:
  instance_name: "Budget Research local search"

server:
  bind_address: "0.0.0.0"
  limiter: false
  public_instance: false

search:
  formats:
    - html
    - json

outgoing:
  request_timeout: 8.0
  max_request_timeout: 12.0
  pool_connections: 50
  pool_maxsize: 20

engines:
  - name: google
    disabled: false
  - name: brave
    disabled: false
  - name: yep
    disabled: false
  - name: mojeek
    disabled: false
  - name: startpage
    disabled: true
  - name: duckduckgo
    disabled: true
  - name: google cse
    disabled: true
  - name: bing
    disabled: true
